name: Build and Package Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Publish Project
        run: dotnet publish ./CrossCore-Lua-Tool/CrossCore-Lua-Tool.csproj -c Release -o CrossCore-Lua-Tool_build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: net8.0
          path: |
            ./CrossCore-Lua-Tool_build
